functions: added invocation metrics
LivePersonInc/developer-center pull request #1634
Opened 2022-05-16 13:04 UTC by lp-mb

2022-05-16 13:15 UTC, Templum requested changes

2022-05-16 13:16 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/monitoring.md
> +### Invocation Metrics
```suggestion
### Invocation Histogram
```

2022-05-16 13:29 UTC, Templum approved these changes

2022-08-19 10:09 UTC, j9t requested changes

2022-08-19 10:09 UTC, j9t commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/monitoring.md
> +### Invocation Histogram
Please add extra line between heading and paragraph (for consistency with rest of document).

2022-08-19 10:28 UTC, j9t commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/monitoring.md
> +### Invocation Histogram
(Per internal conversation, deferring this to approve and merge now.)

2022-08-19 10:28 UTC, Templum commented on pages/Documents/DeveloperTools/LivePersonFunctions/GettingStarted/monitoring.md
> +The invocation histogram allows you to better understand how your function was invoked over time and how it behaved. The graph includes successful and unsuccessful invocations.
```suggestion

The invocation histogram allows you to better understand how your function was invoked over time and how it behaved. The graph includes successful and unsuccessful invocations.
```

2022-08-19 10:28 UTC, Templum reviewed
As requested

2022-08-19 10:29 UTC, merged