finished cookie banner
LivePersonInc/developer-center pull request #1836
Opened 2022-08-22 11:01 UTC by itay1313

2022-08-22 12:24 UTC, j9t requested changes
(This is urgent and important, but no expectation for you to handle this this week.)

2022-08-22 12:24 UTC, j9t commented on _includes/cookie-consent.html
> +    margin-left: 0.5rem;
Please omit leading “0”

2022-08-22 12:24 UTC, j9t commented on _includes/cookie-consent.html
> +    font-family: "Space Grotesk";
Please add generic fallback

2022-08-22 12:24 UTC, j9t commented on _includes/cookie-consent.html
> +<div id="cookie-notice">
Comment: What is the source of this text (and this whole banner code)?

2022-08-22 12:24 UTC, j9t commented on _includes/google_analytics.html
> -<script>
Can you share more, what happened here? This does look suspicious indeed (duplicate UA IDs)—are we just removing it?

2022-08-28 16:45 UTC, itay1313 commented
@j9t Hey Please checkout, have a great week :)

2022-08-29 07:09 UTC, j9t requested changes
Can you make this available on Staging? (Let me know if this is more complicated, but this way we could test and ask for review first.)

2022-08-29 07:09 UTC, j9t commented on _includes/cookie-notice.html
> +    use of this site is subject to our Terms of Use, which include restrictions
I know it’s missing on the screen but please link “Terms of Use” (→ https://www.liveperson.com/policies/terms-of-use/).

2022-08-29 15:11 UTC, j9t requested changes

2022-08-29 15:11 UTC, j9t commented on _includes/cookie-notice.html
> +    <span
This and other locations: Weird inner-tag breaks—is this a tool setting?

Not concerned about content breaks until we agreed on a standard, but let’s not break within tags.

2022-08-30 07:09 UTC, j9t requested changes

2022-08-30 07:09 UTC, j9t commented on _includes/cookie-notice.html
> +      use of this site is subject to our Terms of Use, which include
I’m missing a review comment here—please add a link to our TOU (→ https://www.liveperson.com/policies/apitou/).

2022-08-31 08:41 UTC, j9t requested changes

2022-08-31 08:41 UTC, j9t commented on _includes/google_analytics.html
> -<script>
Please do share :)

2022-08-31 08:41 UTC, j9t commented on _includes/google_analytics.html
> +<script
This file: Please adjust the formatting (no inner-tag breaks).

2022-08-31 08:56 UTC, j9t approved these changes

2022-08-31 09:41 UTC, merged