changed field names
LivePersonInc/developer-center pull request #1842
Opened 2022-08-28 17:57 UTC by itay1313

2022-08-29 10:18 UTC, j9t requested changes
Great update! This looks really solid by now. Suggesting copy tweaks, make this more consistent with the other descriptions. (We can edit more later.)

2022-08-29 10:18 UTC, j9t commented on README.md
> +* `date_published`: This adds the date when it was published. `date_published: 2019/01/30` needs to be added manually
Suggestion:

```
`date_published`: This displays the date when the page was published (needs to be done manually). For example: `date_published: 2019/01/30`.
```

2022-08-29 10:18 UTC, j9t commented on README.md
> +* `date_updated`: Last modified date added. Here's an example: `date_updated: 2022/01/30`
Suggestion:

```
`date_updated`: This defines and shows the date of the last substantial update. For example: `date_updated: 2022/01/30`.
```

2022-08-29 12:05 UTC, itay1313 commented on README.md
> +* `date_updated`: Last modified date added. Here's an example: `date_updated: 2022/01/30`
done

2022-08-29 15:06 UTC, j9t requested changes

2022-08-29 15:06 UTC, j9t commented on README.md
> +* `date_published`: This adds the date when it was published. `date_published: 2019/01/30` needs to be added manually
I can still see the previous version—was the change submitted?

2022-08-30 08:57 UTC, j9t requested changes

2022-08-30 08:57 UTC, j9t commented on README.md
> +* `date_published`: This adds the date when it was published. `date_published: 2019/01/30` needs to be added manually
As mentioned, please make the information here consistent with the other lines, as with

```
`date_published`: This displays the date when the page was published (needs to be done manually). For example: `date_published: 2019/01/30`.
```

2022-08-31 05:40 UTC, j9t requested changes

2022-08-31 05:40 UTC, j9t commented on _layouts/default.html
> +    <link rel="stylesheet" href="css/search.css" />
Sorry I missed this (was not expanded in the view):

Entire file: Check and correct formatting—for some reason, there are many inner-tag breaks.

(If this was intended and you believe we should change this everywhere, let me know—but it seems this was some tooling accident?)

2022-08-31 08:46 UTC, j9t approved these changes

2022-08-31 08:49 UTC, merged