fixed titles
LivePersonInc/developer-center pull request #1865
Opened 2022-09-05 12:51 UTC by itay1313

2022-09-05 13:32 UTC, lkisoslive reviewed
Please keep in mind line 25 - will this be revisited?

2022-09-05 14:11 UTC, itay1313 commented
@lkisoslive I think i will just delete this comment, it doesn't need to be there right?

2022-09-05 14:49 UTC, itay1313 commented on pages/Documents/MessagingChannels/ProactiveMessaging/changelog.md
> -### [v2.36] — 2021-06-04
@j9t  This is the big titles bug DX-145,
so I changed from h2 to h4

2022-09-06 13:07 UTC, j9t requested changes

2022-09-06 13:07 UTC, j9t commented on pages/Documents/MessagingChannels/ProactiveMessaging/changelog.md
> +### Security — in case of vulnerabilities
Please change the heading level (level 4 it seems).

2022-09-06 13:58 UTC, merged